import { CREATE_CONTACT,DELETE_CONTACT,UPDATE_CONTACT} from "../constant/types";

const intialState = {
    contacts:[
        {
          "id": 1,
          "name": "Ahmet Sonuç",
          "username": "Lord",
          "email": "Lordum@gmail.com",
          "inst": "/jahrein",
          "tw": "/jaho07",
          "inst": "/Jahreinlord",
          "lk": "/jaho",
          "git": "jahreinjaho",
          "country" : "Türkiye",
          "street": "Ahmet sk.",
          "suite": "Apt. 556",
          "city": "Antalya",
          "zipcode": "07000",
          "phone": "+905448633525",
          "website": "jahrein.com",
          "company": "Jaharia",
          "aaddress": "Cumhuriyet cad. ahmet sk. apt.556 no:15 d:4 ",      
        },
        {
          "id": 2,
          "name": "Kemal Can Parlak",
          "username": "KenfineMüzisyen",
          "email": "müzisyen@gmail.com",
          "inst": "kendinemüzisyen",
          "tw": "müzisyenkendine",
          "inst": "/kendinemüzisyen",
          "lk": "-",
          "git": "-",
          "country" : "Türkiye",
          "street": "Akbelen Blv.",
          "suite": "Zeytin Apt.",
          "city": "Mersin",
          "zipcode": "33000",
          "phone": "+905236548722",
          "website": "kendine.com",
          "company": "BBL",
          "aaddress": "Akbelen Bul.Zeytin Apt. No:15 D:5 Mersin/Merkez/Türkiye",
         
       
        },
        {
          "id": 3,
          "name": "Ali Kır",
          "username": "Kır",
          "email": "ali.net",
          "inst": "ali_22",
          "tw": "ali_2",
          "inst": "/ali",
          "lk": "-",
          "git": "-",
          "country" : "Almanya",
          "street": "Douglas Extension",
          "suite": "Suite 847",
          "city": "Berlin",
          "zipcode": "030000",
          "phone": "+49595904157",
          "website": "ali.com",
          "company": "AliAS TDİ ŞTİ",
          "aaddress": "Douglas Extension Suite 847 No:56 D:12 Berlin/Almanya",
        },
        {
          "id": 4,
          "name": "Patricia Lebsack",
          "username": "Karianne",
          "email": "Julianne.OConner@kory.org",
          "inst": "Lordum@gmail.com",
          "tw": "Lordum@gmail.com",
          "inst": "Lordum@gmail.com",
          "lk": "Lordum@gmail.com",
          "git": "Lordum@gmail.com",
          "country" : "asdfa",
          "street": "Hoeger Mall",
          "suite": "Apt. 692",
          "city": "South Elvis",
          "zipcode": "53919-4257",
          "phone": "493-170-9623 x156",
          "website": "kale.biz",
          "company": "Robel-Corkery",
          "aaddress": "doldur",

        },
        {
          "id": 5,
          "name": "Chelsey Dietrich",
          "username": "Kamren",
          "email": "Lucio_Hettinger@annie.ca",
          "inst": "Lordum@gmail.com",
          "tw": "Lordum@gmail.com",
          "inst": "Lordum@gmail.com",
          "lk": "Lordum@gmail.com",
          "git": "Lordum@gmail.com",
          "country" : "asdf",
          "street": "Skiles Walks",
          "suite": "Suite 351",
          "city": "Roscoeview",
          "zipcode": "33263",
          "phone": "(254)954-1289",
          "website": "demarco.info",
          "company": "Keebler LLC",
          "aaddress": "doldur",
        },
        {
          "id": 6,
          "name": "Mrs. Dennis Schulist",
          "username": "Leopoldo_Corkery",
          "email": "Karley_Dach@jasper.info",
          "inst": "Lordum@gmail.com",
          "tw": "Lordum@gmail.com",
          "inst": "Lordum@gmail.com",
          "lk": "Lordum@gmail.com",
          "git": "Lordum@gmail.com",
          "country" : "asdf",
          "street": "Norberto Crossing",
          "suite": "Apt. 950",
          "city": "South Christy",
          "zipcode": "23505-1337",
          "phone": "1-477-935-8478 x6430",
          "website": "ola.org",
          "company": "Considine-Lockman",
          "aaddress": "doldur",

        },
        {
          "id": 7,
          "name": "Kurtis Weissnat",
          "username": "Elwyn.Skiles",
          "email": "Telly.Hoeger@billy.biz",
          "inst": "Lordum@gmail.com",
          "tw": "Lordum@gmail.com",
          "inst": "Lordum@gmail.com",
          "lk": "Lordum@gmail.com",
          "git": "Lordum@gmail.com",
          "country" : "asdf",
          "street": "Rex Trail",
          "suite": "Suite 280",
          "city": "Howemouth",
          "zipcode": "58804-1099",
          "phone": "210.067.6132",
          "website": "elvis.io",     
          "company": "Johns Group",
          "aaddress": "doldur",
        },
        {
          "id": 8,
          "name": "Nicholas Runolfsdottir V",
          "username": "Maxime_Nienow",
          "email": "Sherwood@rosamond.me",
          "inst": "Lordum@gmail.com",
          "tw": "Lordum@gmail.com",
          "inst": "Lordum@gmail.com",
          "lk": "Lordum@gmail.com",
          "git": "Lordum@gmail.com",
          "country" : "asdf",
          "street": "Ellsworth Summit",
          "suite": "Suite 729",
          "city": "Aliyaview",
          "zipcode": "45169",
          "phone": "586.493.6943 x140",
          "website": "jacynthe.com",
          "company": "Abernathy Group",
          "aaddress": "doldur",
         
        },
        {
          "id": 9,
          "name": "Glenna Reichert",
          "username": "Delphine",
          "email": "Chaim_McDermott@dana.io",
          "inst": "Lordum@gmail.com",
          "tw": "Lordum@gmail.com",
          "inst": "Lordum@gmail.com",
          "lk": "Lordum@gmail.com",
          "git": "Lordum@gmail.com",
          "country" : "asdf",
          "street": "Dayna Park",
          "suite": "Suite 449",
          "city": "Bartholomebury",
          "zipcode": "76495-3109",
          "phone": "(775)976-6794 x41206",
          "website": "conrad.com",
          "company": "Yost and Sons",
          "aaddress": "doldur",
        },
        {
          "id": 10,
          "name": "Clementina DuBuque",
          "username": "Moriah.Stanton",
          "email": "Rey.Padberg@karina.biz",
          "inst": "Lordum@gmail.com",
          "tw": "Lordum@gmail.com",
          "inst": "Lordum@gmail.com",
          "lk": "Lordum@gmail.com",
          "git": "Lordum@gmail.com",
          "country" : "asdf",
          "street": "Kattie Turnpike",
          "suite": "Suite 198",
          "city": "Lebsackbury",
          "zipcode": "31428-2261",
          "phone": "024-648-3804",
          "website": "ambrose.net",
          "company": "Hoeger LLC",
          "aaddress": "doldur",
        }
      ],
    
};

export const contactReducer = (state = intialState , action) =>{
    switch(action.type){
        case CREATE_CONTACT:
          return{
            ...state,
            contacts:[action.payload, ...state.contacts],
          };
case DELETE_CONTACT:
  console.log("delete",action.payload)
  let arr = state.contacts.filter((contact) => contact.id != action.payload);
  
  return{
    ...state,
    contacts:arr,

  }
  case UPDATE_CONTACT:
    return{
      ...state,
      contacts: state.contacts.map((contact)=>
        contact.id == action.payload.id ? action.payload : contact
      ),
    }
        default:
          return state;
    }
};